language: haskell
env: 
  - PIPATH=./bvdelft/paragon/lib
branches:
  only:
    - master
install:
  - cabal install alex>=2.3
  - cabal install --only-dependencies --enable-tests
notifications:
  email:
    - vandeba@chalmers.se
    - lypai@chalmers.se
